"""AML investigation queue, declared on the generic case engine.

Everything below is configuration. No queue, table, filter, detail-page or
decision code is written here — the platform renders it.
"""

from app.core.rbac import Permission
from app.core.workflow import (
    CaseTypeConfig,
    Column,
    EvidenceTab,
    Filter,
    FilterOption,
    QueuePreset,
    ReasonCode,
    State,
    SummaryField,
    Transition,
    register,
)

TYPOLOGIES = {
    "structuring": "Structuring / smurfing",
    "rapid_movement": "Rapid movement of funds",
    "high_risk_geo": "High-risk jurisdiction exposure",
    "sanctions_nexus": "Possible sanctions nexus",
    "unusual_for_profile": "Activity unusual for customer profile",
    "third_party_funding": "Third-party funding",
}

STATES = (
    State(
        key="new",
        label="New",
        tone="info",
        description="Alert generated by the monitoring rules, not yet picked up.",
    ),
    State(
        key="in_review",
        label="In review",
        tone="warn",
        description="An analyst is actively investigating.",
    ),
    State(
        key="awaiting_info",
        label="Awaiting info",
        tone="neutral",
        description="Blocked on an RFI to the customer or another team.",
    ),
    State(
        key="pending_approval",
        label="Pending approval",
        tone="warn",
        description="SAR recommended; awaiting Compliance Manager sign-off.",
    ),
    State(
        key="sar_filed",
        label="SAR filed",
        tone="danger",
        terminal=True,
        description="Suspicious Activity Report filed with the regulator.",
    ),
    State(
        key="closed_no_action",
        label="Closed - no action",
        tone="success",
        terminal=True,
        description="Investigated and cleared with a documented rationale.",
    ),
)

CLOSE_REASONS = (
    ReasonCode("expected_activity", "Consistent with expected activity"),
    ReasonCode("known_customer", "Explained by known customer context"),
    ReasonCode("duplicate_alert", "Duplicate of another alert"),
    ReasonCode("rule_false_positive", "Rule false positive"),
    ReasonCode("insufficient_evidence", "Insufficient evidence of suspicion"),
)

# Categorical colours for the typology tag, resolved by the shared kit palette.
TYPOLOGY_TONES = (
    ("structuring", "indigo"),
    ("rapid_movement", "sky"),
    ("high_risk_geo", "amber"),
    ("sanctions_nexus", "rose"),
    ("unusual_for_profile", "violet"),
    ("third_party_funding", "teal"),
)

SAR_REASONS = tuple(ReasonCode(key, label) for key, label in TYPOLOGIES.items())

TRANSITIONS = (
    Transition(
        key="claim",
        label="Claim & start review",
        from_states=("new",),
        to_state="in_review",
        permission=Permission.CASE_CLAIM,
        assigns_to_actor=True,
        description="Assign the alert to yourself and begin the investigation.",
    ),
    Transition(
        key="request_info",
        label="Request info",
        from_states=("in_review",),
        to_state="awaiting_info",
        permission=Permission.CASE_REQUEST_INFO,
        variant="outline",
        requires_note=True,
        description="Pause the clock pending an RFI response.",
    ),
    Transition(
        key="resume",
        label="Resume review",
        from_states=("awaiting_info",),
        to_state="in_review",
        permission=Permission.CASE_REQUEST_INFO,
        variant="outline",
    ),
    Transition(
        key="close_no_action",
        label="Close - no action",
        from_states=("in_review", "awaiting_info"),
        to_state="closed_no_action",
        permission=Permission.CASE_CLOSE,
        variant="secondary",
        requires_note=True,
        requires_reason_code=True,
        reason_codes=CLOSE_REASONS,
        description="Clear the alert with a documented rationale.",
    ),
    Transition(
        key="recommend_sar",
        label="Recommend SAR",
        from_states=("in_review", "awaiting_info"),
        to_state="pending_approval",
        permission=Permission.CASE_RECOMMEND,
        variant="default",
        requires_note=True,
        requires_reason_code=True,
        reason_codes=SAR_REASONS,
        description="Send to a Compliance Manager for sign-off.",
    ),
    Transition(
        key="reject_recommendation",
        label="Send back to analyst",
        from_states=("pending_approval",),
        to_state="in_review",
        permission=Permission.CASE_APPROVE,
        variant="outline",
        requires_note=True,
    ),
    Transition(
        key="file_sar",
        label="Approve & file SAR",
        from_states=("pending_approval",),
        to_state="sar_filed",
        permission=Permission.CASE_APPROVE,
        variant="destructive",
        requires_note=True,
        distinct_actor_from="recommend_sar",
        description="Four-eyes: the approver must not be the recommending analyst.",
    ),
    Transition(
        key="reopen",
        label="Reopen",
        from_states=("closed_no_action",),
        to_state="in_review",
        permission=Permission.CASE_REOPEN,
        variant="outline",
        requires_note=True,
    ),
)

COLUMNS = (
    Column(
        "reference",
        "Alert",
        type="reference",
        sortable=True,
        primary=True,
        width="8rem",
    ),
    Column("title", "Summary", type="text"),
    Column("subject_name", "Customer", type="text", sortable=True),
    Column(
        "typology",
        "Typology",
        type="tag",
        width="12rem",
        tones=TYPOLOGY_TONES,
    ),
    Column("amount", "Exposure", type="money", sortable=True, width="8rem"),
    Column("status", "Status", type="status", sortable=True, width="9rem"),
    Column("assignee", "Owner", type="user", width="9rem"),
    Column("due_at", "SLA", type="sla", sortable=True, width="7rem"),
)

FILTERS = (
    Filter("q", "Search", type="search", placeholder="Alert ref, customer, rule..."),
    Filter(
        "status",
        "Status",
        options=tuple(FilterOption(s.key, s.label) for s in STATES),
    ),
    Filter(
        "typology",
        "Typology",
        options=tuple(FilterOption(k, v) for k, v in TYPOLOGIES.items()),
    ),
    Filter(
        "priority",
        "Priority",
        options=(
            FilterOption("high", "High"),
            FilterOption("medium", "Medium"),
            FilterOption("low", "Low"),
        ),
    ),
    Filter("assignee_id", "Owner", options=()),  # populated at request time
)

SUMMARY_FIELDS = (
    SummaryField("subject_name", "Customer", type="text"),
    SummaryField("customer_risk_rating", "Customer risk", type="risk_rating"),
    SummaryField("rule_name", "Triggered rule", type="text"),
    SummaryField("typology", "Typology", type="tag"),
    SummaryField("amount", "Exposure", type="money"),
    SummaryField("window_label", "Detection window", type="text"),
)

EVIDENCE_TABS = (
    EvidenceTab("transactions", "Transactions", component="TransactionEvidence"),
    EvidenceTab("customer", "Customer", component="CustomerEvidence"),
    EvidenceTab("watchlist", "Screening", component="WatchlistEvidence"),
    EvidenceTab("related", "Related alerts", component="RelatedCasesEvidence"),
)

PRESETS = (
    QueuePreset("my_open", "My open alerts", mine=True),
    QueuePreset("unassigned", "Unassigned", filters={"assignee_id": "unassigned"}),
    QueuePreset(
        "pending_approval",
        "Awaiting my approval",
        filters={"status": "pending_approval"},
    ),
    QueuePreset("high_risk", "High priority", filters={"priority": "high"}),
    QueuePreset("all", "All alerts", filters={}),
)

AML = register(
    CaseTypeConfig(
        key="aml",
        label="AML alert",
        plural_label="AML investigation queue",
        description=(
            "Transaction-monitoring alerts triaged by the financial crime team, "
            "from detection through SAR filing."
        ),
        icon="ShieldAlert",
        reference_prefix="AML",
        sla_hours=72,
        states=STATES,
        transitions=TRANSITIONS,
        columns=COLUMNS,
        filters=FILTERS,
        summary_fields=SUMMARY_FIELDS,
        evidence_tabs=EVIDENCE_TABS,
        presets=PRESETS,
    )
)
