/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users */
        get: operations["read_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Case Types */
        get: operations["read_case_types_api_case_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-types/{case_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Case Type */
        get: operations["read_case_type_api_case_types__case_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-types/{case_type}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Cases */
        get: operations["read_cases_api_case_types__case_type__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-types/{case_type}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Metrics */
        get: operations["read_metrics_api_case_types__case_type__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Case */
        get: operations["read_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Transition */
        post: operations["post_transition_api_cases__case_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Comment */
        post: operations["post_comment_api_cases__case_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Assignee */
        post: operations["post_assignee_api_cases__case_id__assignee_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Kind */
            kind: string;
            /** Currency */
            currency: string;
            /** Balance */
            balance: number;
            /** Status */
            status: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
        /** AssignRequest */
        AssignRequest: {
            /** Assignee Id */
            assignee_id?: string | null;
        };
        /** AvailableTransitionOut */
        AvailableTransitionOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** To State */
            to_state: string;
            /** Variant */
            variant: string;
            /** Requires Note */
            requires_note: boolean;
            /** Requires Reason Code */
            requires_reason_code: boolean;
            /** Reason Codes */
            reason_codes: components["schemas"]["ReasonCodeOut"][];
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Disabled Reason */
            disabled_reason?: string | null;
        };
        /** BreakdownItemOut */
        BreakdownItemOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
        };
        /** CaseDetailOut */
        CaseDetailOut: {
            case: components["schemas"]["CaseRowOut"];
            subject: components["schemas"]["CustomerOut"] | null;
            /** Accounts */
            accounts: components["schemas"]["AccountOut"][];
            /** Transactions */
            transactions: components["schemas"]["TransactionOut"][];
            /** Watchlist Hits */
            watchlist_hits: components["schemas"]["WatchlistHitOut"][];
            /** Related Cases */
            related_cases: components["schemas"]["RelatedCaseOut"][];
            /** Events */
            events: components["schemas"]["CaseEventOut"][];
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
            /** Available Transitions */
            available_transitions: components["schemas"]["AvailableTransitionOut"][];
            /** Can Comment */
            can_comment: boolean;
            /** Can Assign Others */
            can_assign_others: boolean;
            /** Can Claim */
            can_claim: boolean;
        };
        /** CaseEventOut */
        CaseEventOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            actor: components["schemas"]["UserOut"] | null;
            /** Transition Key */
            transition_key: string | null;
            /** Transition Label */
            transition_label: string | null;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string | null;
            /** Reason Code */
            reason_code: string | null;
            /** Reason Label */
            reason_label: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** CaseListOut */
        CaseListOut: {
            /** Items */
            items: components["schemas"]["CaseRowOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
        };
        /** CaseRowOut */
        CaseRowOut: {
            /** Id */
            id: string;
            /** Case Type */
            case_type: string;
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Risk Score */
            risk_score: number;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Subject Id */
            subject_id: string | null;
            /** Subject Name */
            subject_name: string | null;
            assignee: components["schemas"]["UserOut"] | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Overdue */
            overdue: boolean;
            /** Hours Remaining */
            hours_remaining: number;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
        };
        /** CaseTypeOut */
        CaseTypeOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Plural Label */
            plural_label: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Reference Prefix */
            reference_prefix: string;
            /** Sla Hours */
            sla_hours: number;
            /** States */
            states: components["schemas"]["StateOut"][];
            /** Transitions */
            transitions: components["schemas"]["TransitionOut"][];
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Filters */
            filters: components["schemas"]["FilterOut"][];
            /** Summary Fields */
            summary_fields: components["schemas"]["SummaryFieldOut"][];
            /** Evidence Tabs */
            evidence_tabs: components["schemas"]["EvidenceTabOut"][];
            /** Presets */
            presets: components["schemas"]["PresetOut"][];
        };
        /** ColumnOut */
        ColumnOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Sortable */
            sortable: boolean;
            /** Width */
            width: string | null;
            /** Primary */
            primary: boolean;
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: string;
            author: components["schemas"]["UserOut"];
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommentRequest */
        CommentRequest: {
            /** Body */
            body: string;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Country */
            country: string;
            /** Segment */
            segment: string;
            /** Risk Rating */
            risk_rating: string;
            /** Kyc Status */
            kyc_status: string;
            /** Is Pep */
            is_pep: boolean;
            /** Occupation */
            occupation: string;
            /** Email */
            email: string;
            /**
             * Onboarded At
             * Format: date-time
             */
            onboarded_at: string;
            /** Lifetime Volume */
            lifetime_volume: number;
        };
        /** EvidenceTabOut */
        EvidenceTabOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Component */
            component: string;
        };
        /** FilterOptionOut */
        FilterOptionOut: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** FilterOut */
        FilterOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Options */
            options: components["schemas"]["FilterOptionOut"][];
            /** Placeholder */
            placeholder: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricTileOut */
        MetricTileOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Format */
            format: string;
            /** Hint */
            hint?: string | null;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Tiles */
            tiles: components["schemas"]["MetricTileOut"][];
            /** By Status */
            by_status: components["schemas"]["BreakdownItemOut"][];
            /** By Typology */
            by_typology: components["schemas"]["BreakdownItemOut"][];
            /** Trend */
            trend: components["schemas"]["TrendPointOut"][];
        };
        /** PresetOut */
        PresetOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Filters */
            filters: {
                [key: string]: string;
            };
            /** Mine */
            mine: boolean;
        };
        /** ReasonCodeOut */
        ReasonCodeOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** RelatedCaseOut */
        RelatedCaseOut: {
            /** Id */
            id: string;
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Risk Score */
            risk_score: number;
        };
        /** StateOut */
        StateOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Tone */
            tone: string;
            /** Terminal */
            terminal: boolean;
            /** Description */
            description: string;
        };
        /** SummaryFieldOut */
        SummaryFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Direction */
            direction: string;
            /** Channel */
            channel: string;
            /** Counterparty Name */
            counterparty_name: string;
            /** Counterparty Country */
            counterparty_country: string;
            /** Description */
            description: string;
            /** Is Flagged */
            is_flagged: boolean;
        };
        /** TransitionOut */
        TransitionOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** To State */
            to_state: string;
            /** Variant */
            variant: string;
            /** Requires Note */
            requires_note: boolean;
            /** Requires Reason Code */
            requires_reason_code: boolean;
            /** Reason Codes */
            reason_codes: components["schemas"]["ReasonCodeOut"][];
            /** Description */
            description: string;
        };
        /** TransitionRequest */
        TransitionRequest: {
            /** Transition */
            transition: string;
            /** Note */
            note?: string | null;
            /** Reason Code */
            reason_code?: string | null;
        };
        /** TrendPointOut */
        TrendPointOut: {
            /** Date */
            date: string;
            /** Opened */
            opened: number;
            /** Closed */
            closed: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Role Label */
            role_label: string;
            /** Job Title */
            job_title: string;
            /** Team */
            team: string;
            /** Initials */
            initials: string;
            /** Permissions */
            permissions: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistHitOut */
        WatchlistHitOut: {
            /** Id */
            id: string;
            /** List Name */
            list_name: string;
            /** Matched Name */
            matched_name: string;
            /** Match Score */
            match_score: number;
            /** Status */
            status: string;
            /** Details */
            details: string;
            /**
             * Screened At
             * Format: date-time
             */
            screened_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_case_types_api_case_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseTypeOut"][];
                };
            };
        };
    };
    read_case_type_api_case_types__case_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_cases_api_case_types__case_type__cases_get: {
        parameters: {
            query?: {
                status?: string | null;
                assignee_id?: string | null;
                priority?: string | null;
                typology?: string | null;
                q?: string | null;
                open_only?: boolean;
                sort?: string;
                direction?: string;
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_metrics_api_case_types__case_type__metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transition_api_cases__case_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_comment_api_cases__case_id__comments_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_assignee_api_cases__case_id__assignee_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
